name: Selenium Tests

on:
  schedule:
    - cron: '0 * * * *' 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Run Selenium script
      run: |
        python ravenro.py
      env:
        USUARIO: ${{ secrets.USUARIO }}
        SENHA: ${{ secrets.SENHA }}
        USUARIO_TULYO: ${{ secrets.USUARIO_TULYO }}
        SENHA_TULYO: ${{ secrets.SENHA_TULYO }}
