name: RavenRO
on: push

jobs:
  tasker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install necessary packages
        run: pip install requests beautifulsoup4 pandas webdriver_manager selenium
        
      - name: Installed package list
        run: apt list --installed
        
      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable
        
      - name: Run the Ragnarok script
        env:
          CHROME_DRIVER_PATH: ${{ env.CHROME_DRIVER_PATH }}  # Use the environment variable
          USUARIO: ${{ secrets.USUARIO }}
          SENHA: ${{ secrets.SENHA }}
        run: python ravenro.py
